// <auto-generated />
using System;
using DWA_AU24_Lab2_Group_11.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DWA_AU24_Lab2_Group_11.Migrations
{
    [DbContext(typeof(FarmTrackContext))]
    [Migration("20260122183629_RealisticSeedData")]
    partial class RealisticSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DWA_AU24_Lab2_Group_11.Models.Crop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GrowingDurationInDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Crop");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GrowingDurationInDays = 90,
                            Name = "Wheat",
                            Type = 120
                        },
                        new
                        {
                            Id = 2,
                            GrowingDurationInDays = 85,
                            Name = "Barley",
                            Type = 89
                        },
                        new
                        {
                            Id = 3,
                            GrowingDurationInDays = 80,
                            Name = "Tomato",
                            Type = 90
                        },
                        new
                        {
                            Id = 4,
                            GrowingDurationInDays = 45,
                            Name = "Lettuce",
                            Type = 90
                        },
                        new
                        {
                            Id = 5,
                            GrowingDurationInDays = 55,
                            Name = "Cucumber",
                            Type = 90
                        },
                        new
                        {
                            Id = 6,
                            GrowingDurationInDays = 70,
                            Name = "Carrot",
                            Type = 40
                        },
                        new
                        {
                            Id = 7,
                            GrowingDurationInDays = 90,
                            Name = "Potato",
                            Type = 23
                        },
                        new
                        {
                            Id = 8,
                            GrowingDurationInDays = 60,
                            Name = "Strawberry",
                            Type = 100
                        },
                        new
                        {
                            Id = 9,
                            GrowingDurationInDays = 30,
                            Name = "Basil",
                            Type = 80
                        },
                        new
                        {
                            Id = 10,
                            GrowingDurationInDays = 40,
                            Name = "Dill",
                            Type = 80
                        });
                });

            modelBuilder.Entity("DWA_AU24_Lab2_Group_11.Models.GrowthHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CropName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DaysBetween")
                        .HasColumnType("int");

                    b.Property<DateTime>("HarvestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PlantingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlantingScheduleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlantingScheduleId");

                    b.ToTable("GrowthHistory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CropName = "Barley",
                            DaysBetween = 85,
                            HarvestDate = new DateTime(2025, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Excellent yield from West Field. Weather conditions were optimal throughout the growing season.",
                            PlantingDate = new DateTime(2025, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlantingScheduleId = 9
                        },
                        new
                        {
                            Id = 2,
                            CropName = "Dill",
                            DaysBetween = 40,
                            HarvestDate = new DateTime(2025, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Good quality herbs. Harvested before first frost. Dried and stored for winter use.",
                            PlantingDate = new DateTime(2025, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlantingScheduleId = 10
                        },
                        new
                        {
                            Id = 3,
                            CropName = "Spring Wheat",
                            DaysBetween = 90,
                            HarvestDate = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Last year's spring wheat harvest. Stored in grain silo. Used for bread flour production.",
                            PlantingDate = new DateTime(2025, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlantingScheduleId = 9
                        });
                });

            modelBuilder.Entity("DWA_AU24_Lab2_Group_11.Models.HarvestTracking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("HarvestDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlantingScheduleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlantingScheduleId");

                    b.ToTable("HarvestTracking");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PlantingScheduleId = 1
                        },
                        new
                        {
                            Id = 2,
                            PlantingScheduleId = 2
                        },
                        new
                        {
                            Id = 3,
                            PlantingScheduleId = 3
                        },
                        new
                        {
                            Id = 4,
                            PlantingScheduleId = 4
                        },
                        new
                        {
                            Id = 5,
                            PlantingScheduleId = 5
                        },
                        new
                        {
                            Id = 6,
                            PlantingScheduleId = 6
                        },
                        new
                        {
                            Id = 7,
                            PlantingScheduleId = 7
                        },
                        new
                        {
                            Id = 8,
                            PlantingScheduleId = 8
                        },
                        new
                        {
                            Id = 9,
                            HarvestDate = new DateTime(2025, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlantingScheduleId = 9
                        },
                        new
                        {
                            Id = 10,
                            HarvestDate = new DateTime(2025, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlantingScheduleId = 10
                        });
                });

            modelBuilder.Entity("DWA_AU24_Lab2_Group_11.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NotificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlantingScheduleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlantingScheduleId");

                    b.ToTable("Notification");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsRead = false,
                            Message = "Your Wheat crop in North Field is ready for harvest in 5 days!",
                            NotificationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlantingScheduleId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsRead = false,
                            Message = "Your Tomato crop in Greenhouse A is ready for harvest in 5 days!",
                            NotificationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlantingScheduleId = 2
                        },
                        new
                        {
                            Id = 3,
                            IsRead = false,
                            Message = "Frost warning! Consider protecting sensitive crops in outdoor areas.",
                            NotificationDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlantingScheduleId = 5
                        },
                        new
                        {
                            Id = 4,
                            IsRead = true,
                            Message = "Your Barley crop in West Field was successfully harvested!",
                            NotificationDate = new DateTime(2025, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlantingScheduleId = 9
                        },
                        new
                        {
                            Id = 5,
                            IsRead = true,
                            Message = "Your Dill crop in Herb Garden was successfully harvested!",
                            NotificationDate = new DateTime(2025, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlantingScheduleId = 10
                        },
                        new
                        {
                            Id = 6,
                            IsRead = true,
                            Message = "Potato planting in South Field is progressing well - 50% growth complete.",
                            NotificationDate = new DateTime(2025, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlantingScheduleId = 3
                        });
                });

            modelBuilder.Entity("DWA_AU24_Lab2_Group_11.Models.PlantingSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CropId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OptimalPlantingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PlantingDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CropId");

                    b.ToTable("PlantingSchedule");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CropId = 1,
                            Location = "North Field",
                            PlantingDate = new DateTime(2025, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CropId = 3,
                            Location = "Greenhouse A",
                            PlantingDate = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CropId = 7,
                            Location = "South Field",
                            PlantingDate = new DateTime(2025, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CropId = 6,
                            Location = "East Garden",
                            PlantingDate = new DateTime(2025, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CropId = 8,
                            Location = "Berry Patch",
                            PlantingDate = new DateTime(2025, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CropId = 4,
                            Location = "Greenhouse B",
                            PlantingDate = new DateTime(2025, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CropId = 9,
                            Location = "Herb Garden",
                            PlantingDate = new DateTime(2025, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CropId = 5,
                            Location = "Greenhouse A",
                            PlantingDate = new DateTime(2025, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CropId = 2,
                            Location = "West Field",
                            PlantingDate = new DateTime(2025, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CropId = 10,
                            Location = "Herb Garden",
                            PlantingDate = new DateTime(2025, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DWA_AU24_Lab2_Group_11.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int?>("PlantingScheduleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TaskDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaskDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlantingScheduleId");

                    b.ToTable("Task");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCompleted = false,
                            TaskDate = new DateTime(2025, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskDescription = "Check all sprinklers and drip lines for damage before spring planting",
                            TaskName = "Inspect irrigation system"
                        },
                        new
                        {
                            Id = 2,
                            IsCompleted = false,
                            TaskDate = new DateTime(2025, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskDescription = "Contact supplier for bulk NPK fertilizer delivery",
                            TaskName = "Order spring fertilizer"
                        },
                        new
                        {
                            Id = 3,
                            IsCompleted = false,
                            PlantingScheduleId = 2,
                            TaskDate = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskDescription = "Deep watering needed in Greenhouse A - check soil moisture first",
                            TaskName = "Water tomatoes"
                        },
                        new
                        {
                            Id = 4,
                            IsCompleted = false,
                            PlantingScheduleId = 1,
                            TaskDate = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskDescription = "Apply nitrogen fertilizer to North Field wheat crop",
                            TaskName = "Fertilize wheat field"
                        },
                        new
                        {
                            Id = 5,
                            IsCompleted = false,
                            PlantingScheduleId = 5,
                            TaskDate = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskDescription = "Remove excess runners to focus plant energy on fruit production",
                            TaskName = "Prune strawberry runners"
                        },
                        new
                        {
                            Id = 6,
                            IsCompleted = false,
                            TaskDate = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskDescription = "Verify heating system is maintaining optimal temperature for seedlings",
                            TaskName = "Check greenhouse temperature"
                        },
                        new
                        {
                            Id = 7,
                            IsCompleted = true,
                            TaskDate = new DateTime(2025, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskDescription = "Insulate walls, check heating system, clean glass panels",
                            TaskName = "Prepare greenhouse for winter"
                        },
                        new
                        {
                            Id = 8,
                            IsCompleted = true,
                            TaskDate = new DateTime(2025, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskDescription = "Placed order with Nordic Seeds AB for spring planting",
                            TaskName = "Order seeds for spring"
                        },
                        new
                        {
                            Id = 9,
                            IsCompleted = true,
                            PlantingScheduleId = 9,
                            TaskDate = new DateTime(2025, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskDescription = "Complete harvest from West Field - store in grain silo",
                            TaskName = "Harvest barley crop"
                        },
                        new
                        {
                            Id = 10,
                            IsCompleted = true,
                            PlantingScheduleId = 7,
                            TaskDate = new DateTime(2025, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskDescription = "Transplant basil seedlings to herb garden raised beds",
                            TaskName = "Plant basil seedlings"
                        });
                });

            modelBuilder.Entity("DWA_AU24_Lab2_Group_11.Models.WeatherData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("Humidity")
                        .HasColumnType("float");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("WeatherData");
                });

            modelBuilder.Entity("DWA_AU24_Lab2_Group_11.Models.GrowthHistory", b =>
                {
                    b.HasOne("DWA_AU24_Lab2_Group_11.Models.PlantingSchedule", "PlantingSchedule")
                        .WithMany()
                        .HasForeignKey("PlantingScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlantingSchedule");
                });

            modelBuilder.Entity("DWA_AU24_Lab2_Group_11.Models.HarvestTracking", b =>
                {
                    b.HasOne("DWA_AU24_Lab2_Group_11.Models.PlantingSchedule", "PlantingSchedule")
                        .WithMany()
                        .HasForeignKey("PlantingScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlantingSchedule");
                });

            modelBuilder.Entity("DWA_AU24_Lab2_Group_11.Models.Notification", b =>
                {
                    b.HasOne("DWA_AU24_Lab2_Group_11.Models.PlantingSchedule", "PlantingSchedule")
                        .WithMany()
                        .HasForeignKey("PlantingScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlantingSchedule");
                });

            modelBuilder.Entity("DWA_AU24_Lab2_Group_11.Models.PlantingSchedule", b =>
                {
                    b.HasOne("DWA_AU24_Lab2_Group_11.Models.Crop", "Crop")
                        .WithMany("PlantingSchedules")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");
                });

            modelBuilder.Entity("DWA_AU24_Lab2_Group_11.Models.Task", b =>
                {
                    b.HasOne("DWA_AU24_Lab2_Group_11.Models.PlantingSchedule", "PlantingSchedule")
                        .WithMany("Tasks")
                        .HasForeignKey("PlantingScheduleId");

                    b.Navigation("PlantingSchedule");
                });

            modelBuilder.Entity("DWA_AU24_Lab2_Group_11.Models.Crop", b =>
                {
                    b.Navigation("PlantingSchedules");
                });

            modelBuilder.Entity("DWA_AU24_Lab2_Group_11.Models.PlantingSchedule", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
